//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdplacementTbl
    {
        public int IDAdPlacement { get; set; }
        public Nullable<int> IDPlacement { get; set; }
        public Nullable<int> IDAd { get; set; }
        public Nullable<int> IDPage { get; set; }
        public Nullable<double> LeftPositionX { get; set; }
        public Nullable<double> LeftPositionY { get; set; }
    
        public virtual AdTbl AdTbl { get; set; }
        public virtual PageTbl PageTbl { get; set; }
        public virtual PlacementTbl PlacementTbl { get; set; }
    }
}
