//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdTbl()
        {
            this.AdplacementTbl = new HashSet<AdplacementTbl>();
        }
    
        public int IDAd { get; set; }
        public Nullable<int> IDSize { get; set; }
        public Nullable<int> IDPreferencePage { get; set; }
        public Nullable<int> IDPreferenceSheet { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IsGenizah { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public Nullable<int> IsEmbedded { get; set; }
        public Nullable<double> LeftPositionX { get; set; }
        public Nullable<double> LeftPositionY { get; set; }
        public Nullable<int> IDDeal { get; set; }
        public Nullable<int> IDPage { get; set; }
        public Nullable<int> IDAdImage { get; set; }
    
        public virtual AdImageTbl AdImageTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdplacementTbl> AdplacementTbl { get; set; }
        public virtual CategoryTbl CategoryTbl { get; set; }
        public virtual DealTbl DealTbl { get; set; }
        public virtual PageTbl PageTbl { get; set; }
        public virtual PreferenceSheetTbl PreferenceSheetTbl { get; set; }
        public virtual PreferencePageTbl PreferencePageTbl { get; set; }
        public virtual SizeTbl SizeTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
