//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealTbl()
        {
            this.AdTbl = new HashSet<AdTbl>();
        }
    
        public int IDDeal { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> IDDealType { get; set; }
        public Nullable<int> IDPageType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdTbl> AdTbl { get; set; }
        public virtual DealTypeTbl DealTypeTbl { get; set; }
        public virtual PageTypeTbl PageTypeTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
