//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdsPlacementEntities : DbContext
    {
        public AdsPlacementEntities()
            : base("name=AdsPlacementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdImageTbl> AdImageTbl { get; set; }
        public virtual DbSet<AdplacementTbl> AdplacementTbl { get; set; }
        public virtual DbSet<AdTbl> AdTbl { get; set; }
        public virtual DbSet<CategoryTbl> CategoryTbl { get; set; }
        public virtual DbSet<DealTbl> DealTbl { get; set; }
        public virtual DbSet<DealTypeTbl> DealTypeTbl { get; set; }
        public virtual DbSet<PageTbl> PageTbl { get; set; }
        public virtual DbSet<PageTypeTbl> PageTypeTbl { get; set; }
        public virtual DbSet<PermissionTbl> PermissionTbl { get; set; }
        public virtual DbSet<PlacementTbl> PlacementTbl { get; set; }
        public virtual DbSet<PreferencePageTbl> PreferencePageTbl { get; set; }
        public virtual DbSet<PreferenceSheetTbl> PreferenceSheetTbl { get; set; }
        public virtual DbSet<PriorityTbl> PriorityTbl { get; set; }
        public virtual DbSet<ScoreTbl> ScoreTbl { get; set; }
        public virtual DbSet<SheetTbl> SheetTbl { get; set; }
        public virtual DbSet<SheetTypeTbl> SheetTypeTbl { get; set; }
        public virtual DbSet<SizeTbl> SizeTbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserTbl> UserTbl { get; set; }
    }
}
