//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageTbl()
        {
            this.AdplacementTbl = new HashSet<AdplacementTbl>();
            this.AdTbl = new HashSet<AdTbl>();
        }
    
        public int IDPage { get; set; }
        public Nullable<int> PageNum { get; set; }
        public Nullable<int> IDPageType { get; set; }
        public Nullable<int> IsExternal { get; set; }
        public Nullable<int> IDSheet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdplacementTbl> AdplacementTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdTbl> AdTbl { get; set; }
        public virtual PageTypeTbl PageTypeTbl { get; set; }
    }
}
