//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheetTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SheetTbl()
        {
            this.PlacementTbl = new HashSet<PlacementTbl>();
        }
    
        public int IDSheet { get; set; }
        public Nullable<System.DateTime> DateDistribution { get; set; }
        public Nullable<int> NumOfPage { get; set; }
        public Nullable<int> NumOfSheet { get; set; }
        public Nullable<int> IDSheetType { get; set; }
        public Nullable<int> IDSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacementTbl> PlacementTbl { get; set; }
        public virtual SheetTypeTbl SheetTypeTbl { get; set; }
        public virtual SizeTbl SizeTbl { get; set; }
    }
}
